env: dev                              # Affects log level and a few other things

mail:
  domain: mailwhale.dev               # Your server's domain name
  spf:
    check: true
    authorized_ips:                   # Option 1: Require specific IPs to be allowed by a sender domain's SPF record
    authorized_delegates:             # Option 2: Require certain domains to be set as an 'include' in a sender domain's SPF record

web:
  listen_v4: '127.0.0.1:3000'         # Where to make the http server listen
  cors_origins:
    - 'http://localhost:5000'

smtp:
  host: 'localhost'
  port: 465
  username: 'you@example.org'
  password: 'your secret password'
  tls: true                           # Whether to connect via SSL/TLS (set 'false' for STARTTLS)

store:
  path: 'data.gob.db'

security:
  pepper: 'sshhh'
  seed_users:
    - email: 'admin@local.host'
      password: 'admin'