env: dev                              # Affects log level and a few other things

mail:
  domain: mailwhale.dev               # Your server's domain name
  verify_senders: true                # Whether to send verification mail when adding new sender addresses

web:
  public_url: 'http://localhost:3000' # Publicly available URL of your instance, required for callback links via e-mail
  listen_v4: '127.0.0.1:3000'         # Where to make the http server listen
  cors_origins:
    - 'http://localhost:5000'

smtp:
  host: 'localhost'
  port: 465
  username: 'you@example.org'
  password: 'your secret password'
  tls: true                           # Whether to connect via SSL/TLS (set 'false' for STARTTLS)

store:
  path: 'data.gob.db'

security:
  pepper: 'sshhh'                     # Change this!
  allow_signup: true